// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjOP2pDHYDQxSU1MbtrinYUsPNtycze8k',
    appId: '1:1091700744691:web:80115f34f334d7739c3286',
    messagingSenderId: '1091700744691',
    projectId: 'spin-and-earn-money-24634',
    authDomain: 'spin-and-earn-money-24634.firebaseapp.com',
    storageBucket: 'spin-and-earn-money-24634.firebasestorage.app',
    measurementId: 'G-5GP6N401CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSC4WIIsbultS4NmnKYgJ5fa_16cLt-5I',
    appId: '1:1091700744691:android:959bd6a71235f7719c3286',
    messagingSenderId: '1091700744691',
    projectId: 'spin-and-earn-money-24634',
    storageBucket: 'spin-and-earn-money-24634.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANvVuX1DUsjf1gfSWyShTeL2hFrX70ViM',
    appId: '1:1091700744691:ios:5bf87c55df1912049c3286',
    messagingSenderId: '1091700744691',
    projectId: 'spin-and-earn-money-24634',
    storageBucket: 'spin-and-earn-money-24634.firebasestorage.app',
    androidClientId: '1091700744691-c2ia3kbgpcjmcsbuqvmv9i2ipqlltl4c.apps.googleusercontent.com',
    iosClientId: '1091700744691-a3p67ec1q4nm865jnrrqhfatir3v42mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.spinAndEarn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANvVuX1DUsjf1gfSWyShTeL2hFrX70ViM',
    appId: '1:1091700744691:ios:5bf87c55df1912049c3286',
    messagingSenderId: '1091700744691',
    projectId: 'spin-and-earn-money-24634',
    storageBucket: 'spin-and-earn-money-24634.firebasestorage.app',
    androidClientId: '1091700744691-c2ia3kbgpcjmcsbuqvmv9i2ipqlltl4c.apps.googleusercontent.com',
    iosClientId: '1091700744691-a3p67ec1q4nm865jnrrqhfatir3v42mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.spinAndEarn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjOP2pDHYDQxSU1MbtrinYUsPNtycze8k',
    appId: '1:1091700744691:web:fc2ba7a59ed3717e9c3286',
    messagingSenderId: '1091700744691',
    projectId: 'spin-and-earn-money-24634',
    authDomain: 'spin-and-earn-money-24634.firebaseapp.com',
    storageBucket: 'spin-and-earn-money-24634.firebasestorage.app',
    measurementId: 'G-404EK6DMRT',
  );
}
